#!/usr/bin/env bash
source "$(dirname $0)/../common/functions"
# Reset bash mode from importing the functions
set +exo pipefail
# Fail on equation failure
set -e

REDISIMAGE=$(cat redisimage)

# Build redis-server docker image
if docker inspect "$REDISIMAGE" >/dev/null 2>/dev/null; then
	docker pull "$REDISIMAGE"
fi
